### PR TITLE
Update Dynmap dependency

### PR DESCRIPTION
**Pull request by ghost**
Update Dynmap dependency to Dynmap-3.0.1-spigot.

### CODE REVIEW

**Comment by MyzelYam** [comment]
Hey, including dynmap as a local jar file was just a last-resort solution. Do you know of reliable maven repositories including the last dynmap release? Adding it like that would be much better for the build stability.

**Comment by Ashesh3** [comment]
> Hey, including dynmap as a local jar file was just a last-resort solution. Do you know of reliable maven repositories including the last dynmap release? Adding it like that would be much better for the build stability.

On a side note, the  [essentials-repo](http://repo.ess3.net/content/groups/essentials) is also unavailable for quite some time now, including people complaining about this rep all over the internet for instability.

I couldn't find an exact alternative, so for my own build i had to manually add Essentials and ProtoLib jar file as manual dependencies.

**Comment by bananasmoothii** [comment]
> Do you know of reliable maven repositories including the last dynmap release? Adding it like that would be much better for the build stability.
Hello, latest dynmap build is here: https://dynmap.us/builds/dynmap/Dynmap-3.1-SNAPSHOT-forge-1.16.4.jar  . Also, I am still shown on the map when I am vanished, could you fix it at some time ? Thanks in advance.

**Comment by Iaiao** [comment]
> Do you know of reliable maven repositories including the last dynmap release? Adding it like that would be much better for the build stability.

Their README.md says https://repo.mikeprimm.com

**Comment by LeonMangler** [comment]
I tried this but it can't find it:
`<repository>
            <id>dynmap-repo</id>
            <url>https://repo.mikeprimm.com</url>
</repository>
`
`
 <dependency>
            <groupId>us.dynmap</groupId>
            <artifactId>DynmapCoreAPI</artifactId>
            <version>3.1</version>
</dependency>`
Confusing is that when I'm browsing the repo with a web browser I can find it just fine. Maybe it's time to switch to gradle...

**Pull request closed without merging**
